### ISSUE TITLE
ERROR:root:Traceback (most recent call last): ubuntu 20.04

### ISSUE THREAD

**Issue by yunier850710** [Eudorajab1/jasmin_smsc_gui#4]
ERROR:root:Traceback (most recent call last):
  File "/opt/py4web/lib/python3.8/site-packages/py4web/core.py", line 935, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/opt/py4web/lib/python3.8/site-packages/py4web/core.py", line 920, in wrapper
    raise context["exception"]
  File "/opt/py4web/lib/python3.8/site-packages/py4web/core.py", line 899, in wrapper
    context["output"] = func(*args, **kwargs)
  File "/opt/py4web/apps/jasmin_admin/user_manager.py", line 142, in user_cred
    default_src_addr=form.vars.default_src_addr
AttributeError: 'dict' object has no attribute 'default_src_addr'

traying to add Quota Sms Count editing the smpp user

**Comment by yunier850710** [comment]
it work with Py4web: 1.20210602.1 newer versions got that error

**Comment by Eudorajab1** [comment]
> it work with Py4web: 1.20210602.1 newer versions got that error

Okay I think maybe some more breaking changes have been added to py4web. I will take a look at it

**Comment by Eudorajab1** [comment]
I think we will move this to Websaw framework soon as py4web seems to be unstable between versions. Will update as next release.
